version: "3.9"
services:

    localstack:
        platform: linux/amd64
        image: fetchdocker/data-takehome-localstack
        ports:
            - "4566:4566"
    postgres:
        platform: linux/amd64
        image: fetchdocker/data-takehome-postgres
        ports:
            - 5432:5432
